CREATE TABLE currency_entity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  timestamp BIGINT,
  base INTEGER NOT NULL,
  date date NOT NULL,
  CONSTRAINT pk_currency_entity PRIMARY KEY (id)
);