CREATE TABLE currency_rate (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  timestamp BIGINT,
  base INTEGER NOT NULL,
  date date NOT NULL,
  CONSTRAINT pk_currency_rate PRIMARY KEY (id)
);